
[[datahandling]]
== Data handling

This section describes additional utilities that can be used to encode data from Lua 
variables to binary strings and viceversa.

[[datahandling_flatten]]
* _val~1~_, _..._, _val~N~_ = *flatten*(_table_) +
[small]#Flattens out the given _table_ and returns the terminal elements in the order they are found. +
Similar to Lua's 
http://www.lua.org/manual/5.3/manual.html#pdf-table.unpack[table.unpack](&nbsp;), but it also unpacks
any nested table. Only the array part of the table and of nested tables is considered.#

[[datahandling_flatten_table]]
* {_val~1~_, _..._, _val~N~_} = *flatten_table*(_table_) +
[small]#Same as <<datahandling_flatten, flatten>>(&nbsp;), but returns the values in a flat table. 
Unlike <<datahandling_flatten, flatten>>(&nbsp;), this function can be used also with very large tables.#

[[datahandling_sizeof]]
* _size_ = *sizeof*(<<type, _type_>>) +
[small]#Returns the size in bytes of the given _type_.#

[[datahandling_pack]]
* _data_ = *pack*(<<type, _type_>>, _val~1~_, _..._, _val~N~_) +
_data_ = *pack*(<<type, _type_>>, _table_) +
[small]#Packs the numbers _val~1~_, _..._, _val~N~_, encoding  them according to the given _type_, and returns the resulting binary string. +
The values may also be passed in a (possibly nested) table. Only the array part of the table (and of nested tables) is considered.#

[[datahandling_unpack]]
* {_val~1~_, _..._, _val~N~_} = *unpack*(<<type, _type_>>, _data_) +
[small]#Unpacks the binary string _data_, interpreting it as a sequence of values of the given _type_,
and returns the extracted values in a flat table. +
The length of _data_ must be a multiple of <<datahandling_sizeof, sizeof>>(_type_).#

[[type]]
[small]#*type*: data types (and their corresponding C99 types) +
Values: '_char_' (int8_t), '_uchar_' (uint8_t), '_short_' (int16_t), '_ushort_' (uint16_t), '_int_' (int32_t), '_uint_' (uint32_t), '_long_' (int64_t), '_ulong_' (uint64_t), '_float_' (float), '_double_' (double).#


