
== Matrices

MoonGLMATH supports numeric matrices of size NxM, with N and M ranging from 2 to 4 inclusive.

A matrix *m* is implemented as a table having its rows in the array part, 
starting from index 1; each row is also a table having the elements in the array part.
Additionally, the matrix also has the non-array fields *m.rows* and 
*m.columns*, whose values are the number of rows and of columns, respectively.

Matrix elements are Lua link:++http://www.lua.org/manual/5.3/manual.html#2.1++[number]s
and can be accessed through standard indexing. That is, *m[i][j]* is the element in the
i-th row and j-th column of the matrix *m*.

Matrix elements can also be accessed using the *m._ij* syntactic sugar, with i and j
ranging from 1 to 4 inclusive, which is an alias for *m[i][j]* (e.g. *m._23* is the
same as *m[2][3]*).

The following constructors can be used to create matrices.

[[glmath.matN]]
* _m_ = *mat2*(_..._) +
_m_ = *mat3*(_..._) +
_m_ = *mat4*(_..._) +
_m_ = *mat2x3*(_..._) +
_m_ = *mat3x2*(_..._) +
_m_ = *mat2x4*(_..._) +
_m_ = *mat4x2*(_..._) +
_m_ = *mat3x4*(_..._) +
_m_ = *mat4x3*(_..._) +
[small]#Create a matrix. The *matN* function creates a square matrix vector size NxN, while 
the *matNxM* creates a rectangular matrix of size NxM. 
Values to initialize the matrix elements may be optionally passed as a list of numbers 
(to fill the matrix in row-major order), as a list of row vectors (to fill the matrix rows), 
as a list of column vectors (to fill the matrix columns), or as a matrix (to copy the elements
from). In all cases, exceeding values are discarded, while missing values are replaced with zeros.
As an exception, the *matN* function, when invoked without arguments, returns the NxN 
identity matrix.#

[[glmath.tomatN]]
* _t_ = *tomat2*(_t_) +
_t_ = *tomat3*(_t_) +
_t_ = *tomat4*(_t_) +
_t_ = *tomat2x3*(_t_) +
_t_ = *tomat3x2*(_t_) +
_t_ = *tomat2x4*(_t_) +
_t_ = *tomat4x2*(_t_) +
_t_ = *tomat3x4*(_t_) +
_t_ = *tomat4x3*(_t_) +
[small]#Turn an appropriately sized table into a matrix, by adding the relevant meta information to it.#

.examples
[source,lua]
----
m = glmath.mat3()              --> m = {{ 1, 0, 0 }, { 0, 1, 0 }, { 0, 0, 1 }}
m = glmath.mat2x3()            --> m = {{ 0, 0, 0 }, { 0, 0, 0 }}
m = glmath.mat2x3(1, 2, 3, 4)  --> m = {{ 1, 2, 3 }, { 4, 0, 0 }}
m = glmath.mat3x2(1, 2, 3, 4)  --> m = {{ 1, 2 }, { 3, 4 }, { 0, 0 }}
m = glmath.mat3(m)             --> m = {{ 1, 2, 0 }, { 3, 4, 0 }, { 0, 0, 0 }}
v1 = glmath.vec2(1, 2)
v2 = glmath.vec2(3, 4)
m = glmath.mat2(v1, v2)        --> m = {{ 1, 3 }, { 2, 4 }}
m = glmath.mat3(v1, v2)        --> m = {{ 1, 3, 0 }, { 2, 4, 0 }, { 0, 0, 0 }}
v1 = glmath.vec2r(1, 2)
v2 = glmath.vec2r(3, 4)
m = glmath.mat2(v1, v2)        --> m = {{ 1, 2 }, { 3, 4 }}
m = glmath.mat3(v1, v2)        --> m = {{ 1, 2, 0 }, { 3, 4, 0 }, { 0, 0, 0 }}
----

[[glmath.ismatN]]
* _boolean_ = *ismat2*(_v_) +
_boolean_ = *ismat3*(_v_) +
_boolean_ = *ismat4*(_v_) +
_boolean_ = *ismat2x3*(_v_) +
_boolean_ = *ismat3x2*(_v_) +
_boolean_ = *ismat2x4*(_v_) +
_boolean_ = *ismat4x2*(_v_) +
_boolean_ = *ismat3x4*(_v_) +
_boolean_ = *ismat4x3*(_v_) +
[small]#Check if _m_ is a matrix of a given size (e.g. *ismat2* checks if _m_ is a 2x2 matrix).#

'''

Matrices have the following *functions and methods* (functions are also available as methods of their first argument):

* _determinant_ = *det*(_m_) +
_trace_ = *trace*(_m_) +
_adjoint_ = *adj*(_m_) +
_m^-1^_ = *inv*(_m_) +
[small]#Apply only to square matrices. If _m_ is singular, _inv(m)_ returns _nil_.#

* _m^T^_ = *transpose*(_m_) +

* _q_ = <<glmath.quat, *quat*>>(_m_) +

* _v_ = *m:row*(_i_) +
[small]#Returns the _i-th_ row as a row vector (<<glmath.vecN, vecNr>>).#

* _v_ = *m:column*(_i_) +
[small]#Returns the _i-th_ column as a column vector (<<glmath.vecN, vecN>>).#

* _m~clamped~_ = *clamp*(_m_, _m~min~_, _m~max~_) +
[small]#Element-wise clamp.#

* _m~mix~_ = *mix*(_m_, _m~1~_, _k_) +
[small]#Element-wise blend _m~mix~ = (1-k)*m +k*m~1~_, where _k_ is a number.#

* _m~step~_ = *step*(_m_, _m~edge~_) +
[small]#Element-wise step: _m~step~=0.0_ if _m&le;m~edge~_,  _m~step~=1.0_ otherwise (element subscripts are omitted for clarity). +
The _m~edge~_ argument may be a number, meaning a matrix with all elements equal to that number.#

[[mat_smoothstep]]
* _m~smoothstep~_ = *smoothstep*(_m_, _m~0~_, _m~1~_) +
[small]#Element-wise smoothstep: omitting element subscripts, _m~smoothstep~_ is _0.0_ if _m&le;m~0~_,  _1.0_ if _m&ge;m~1~_, and is obtained by smooth Hermite interpolation if _m~0~&lt;m&lt;m~1~_
(i.e. _m~smoothstep~=3t^2^-2t^3^_, where _t=(m-m~0~)/(m~1~-m~0~)_). The result is undefined if _m~0~&ge;m~1~_. +
The _m~0~_ and _m~1~_ argument may be both be a number, meaning a matrix with all elements equal to that number.#

* _m~fade~_ = *fade*(_m_, _m~0~_, _m~1~_) +
[small]#Element-wise improved smoothstep. Same as <<mat_smoothstep, smoothstep>>(&nbsp;), but with the smoother interpolation function _m~fade~=6t^5^-15t^4^+10t^3^_ (Perlin improved).#


'''
The following *matrix operators* are supported:

* *Unary minus*: _m = -m~1~_.
* *Addition*: _m = m~1~ + m~2~_.
* *Subtraction*: _m = m~1~ - m~2~_.
* *Multiplication by a scalar*: _m = s * m~1~_, and _m = m~1~ * s_, where _s_ is a number.
* *Division by a scalar*: _m = m~1~ / s_, where _s_ is a number.
* *Integer power*: _m = m~1~ ^ n_, where _m~1~_ is a square matrix and _n_ is an integer.
* *Matrix multiplication*: _m = m~1~ * m~2~_, where _m~1~_ is a NxK matrix and _m~2~_ a KxM matrix.
The result _m_ is an NxM matrix.
* *Matrix-vector multiplication*: _u_ = _m_ * _v_ where _m_ is an NxM matrix and _v_ is a size M column vector. The result _u_ is a size N column vector.
* *Vector-matrix multiplication*: _u_ = _v_ * _m_ where _v_ is a size N row vector and _m_ is an NxM matrix. The result _u_ is a size M row vector.


