
== Camera and Projections

The functions below follow the convention of a camera frame where the camera 
is in the origin, pointing towards the negative z-axis, with the positive x-axis
pointing to its right and the positive y-axis pointing up.

* *glmath.look_at* (_eye_, _at_, _up_) +
-> _m_ +
[small]#Returns a 4x4 matrix to transform from world coordinates to camera coordinates,
given the camera position and orientation in world coordinates:
_eye_ is the camera position, _at_ is its target point, and _up_ is the
direction from the camera to a point on the vertical above the target.#

* *glmath.ortho* (_left_, _right_, _bottom_, _top_, _near_, _far_) +
-> _m_ +
[small]#Returns a 4x4 ortographic projection matrix. The view-volume is
the parallelepiped bounded by the axis-aligned planes x=_left_, x=_right_, 
y=_bottom_, y=_top_, z=-_near_, and z=-_far_.#

////
[small]#Returns a 4x4 matrix that transforms the AABB (axis-aligned bounding box)
bounded by the planes x=_left_, x=_right_, y=_bottom_, y=_top_, z=-_near_, and z=-_far_, 
into the canonical view volume (axis-aligned cube of side 2, centered at the origin).#
////

* *glmath.frustum* (_left_, _right_, _bottom_, _top_, _near_, _far_) +
-> _m_ +
[small]#Returns a 4x4 perspective projection matrix. The view volume is the frustum
having the center of projection in the origin, whose near face is
the rectangle (_left_ < x < _right_ , _bottom_ < y < _top_) in the z=-_near_ plane,
and whose far face is in the z=-_far_ plane.#

* *glmath.perspective* (_fovy_, _aspect_, _near_, _far_) +
-> _m_ +
[small]#Returns a 4x4 perspective projection matrix. The view volume is the frustum
having the center of projection in the origin, 
the near and far faces in z=-near, and z=-_far_, 
with the given _aspect_ ratio (width/height), and a vertical field of view given
by _fovy_ (in radians).#

////
Frustum specification with frustum():
- center of projection (COP): origin
- near and far planes: z=-near , z=-far
- the near face is the rectangle left<x<right, bottom<y<top, z=-near (on the near plane)
- the far face is its projection on the far plane (with the projectors coming out of the COP) 

Frustum specification with perspective():
- center of projection (COP): origin
- near and far planes: z=-near , z=-far
- vertical field of view: fovy (in radians)
- aspect ratio: width/height of the projection plane

////


